AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Task2TemplateName:
    Type: String
    Default: Task2

  Task2SubjectPart:
    Type: String
    Default: Validation of Service Portfolio Owners in Service Now

  Task2HtmlPart:
    Type: String
    Default: "<h1>Validation of Service Portfolio Owners in Service Now</h1><p>Dear {{contact}}, </br>Please could you reply to this email to confirm that you are still the Service Portfolio Ownerof the following portfolios(s):</p><ul>{{#each applications}}<li>{{application}}</li>{{/each}}</ul><p>Kind regards,</p><p>{{sender}}</p>"

Resources: 
  ReportsBucket:
    Type : AWS::S3::Bucket
    Name: reports-parser-report-bucket

  ContactTable:
    Type: AWS::Serverless::SimpleTable   

  ReportParser:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./src/report_parser
      Handler: handler.handler
      Layers:
        - arn:aws:lambda:eu-west-1:762461925189:layer:pandas:6
      Timeout: 10
      Environment:
        Variables:
          EMAIL_LOOKUP_TABLE: !Ref ContactTable
          TASK2_TOPIC_ARN:    
           Fn::GetAtt:
             - Task2
             - Outputs.TopicArn
      Policies:
      - Statement:
        - Sid: S3GetObject
          Effect: Allow
          Action:
          - s3:GetObject
          Resource: '*'
      - DynamoDBReadPolicy:
          TableName: !Ref ContactTable
      - SNSPublishMessagePolicy:
            TopicName:            
              Fn::GetAtt:
                - Task2
                - Outputs.TopicName
      Events:
        ReportAdded:
          Type: S3
          Properties:
            Bucket: !Ref ReportsBucket
            Events: s3:ObjectCreated:*
            
  Task2:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./sam-task-lambda-template.yml
      Parameters:
        TemplateName: Task2
        SubjectPart: Validation of Service Portfolio Owners in Service Now
        HtmlPart: "<h1>Validation of Service Portfolio Owners in Service Now</h1><p>Dear {{contact}}, </br>Please could you reply to this email to confirm that you are still the Service Portfolio Ownerof the following portfolios(s):</p><ul>{{#each applications}}<li>{{application}}</li>{{/each}}</ul><p>Kind regards,</p><p>{{sender}}</p>"
        CodeUri: ./src/task_2_email
        TopicName: Task2